### ISSUE TITLE
Readme.md require name is wrong

### ISSUE THREAD

**Issue by jonsamwell** [VictorQueiroz/gulp-ng-templates#1]
Hey,

Thanks for the plugin!

Just a tiny issue in the Readme file.  I had to change this line

var ngTemplates = require('gulp-ng-templates');

to this:

var ngTemplates = require('gulp-ngtemplates');

Thanks.

**Comment by VictorQueiroz** [comment]
Then you didn't download the right module or there is something wrong with your node_modules folders...
