### ISSUE TITLE
Ensure statements to add to template cache are in same order as filestream input

### ISSUE THREAD

**Issue by thethomaseffect** [VictorQueiroz/gulp-ng-templates#2]
I'm using `gulp-ng-templates` as part of a workflow that combines it with minified scripts, revs the contents and the file is added to index.html. However, right now the outputted module for gulp-ng-templates has the statements that add each file to $templatecache is a different order everytime it's run. The problem with this is it means that the client connecting downloads scripts everytime a new build is deployed. I've worked around this by only running the task if the src files have actually changed but it would be nice to avoid this. 

The following code would ideally lead to the same order every single time:

``` javascript
        // ... some gulp.src and other tasks
        .pipe(sort())
        .pipe(ngTemplates({
            // settings
        }))
```

If for some reason this is impossible to do by default a new `{ sort: function(path){ return /*comparator */ } }` option that does would be great.

**Comment by thethomaseffect** [comment]
This actually may have been caused by another plugin, close if you're sure they're always in the same order right now

**Comment by VictorQueiroz** [comment]
Well, you should use `gulp-sort` if you want your templates in a strict order. I'm pretty sure it was caused by another plugin.
