### ISSUE TITLE
TypeError: gulp-ng-templates is not a function

### ISSUE THREAD

**Issue by nipmarsh** [VictorQueiroz/gulp-ng-templates#9]
Since the 1.01 update gulp-ng-templates does not work anymore and throw TypeError: ngTemplates is not a function... I'm using Webstorm 2018.3.2 for my project.
Here is my gulp task

```
gulp.task('cache-templates', function () {
    return gulp.src(['public/partials/**/*.html'])
        .pipe(ngTemplates({
            filename: 'templates.js',
            module: 'app',
            standalone: false,
            htmlMinifier: {
                collapseWhitespace: true,
                conservativeCollapse: true
            },
            path: function (path, base) {
                return 'partials/' + path.replace(base, '');
            }
        }))
        .pipe(gulp.dest('public/js'));
});
```

**Comment by miroslavrehor** [comment]
Same problem in my project.

**Comment by VictorQueiroz** [comment]
I'm supposing that most use cases are not using ES6 modules. So I just exported the default function using CommonJS module system as it also matches the README.md instructions. It should be fixed now! Let me know if you have more issues.
